security:
    encoders:
        App\Entity\Usuario:
            algorithm: auto

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER

    # https://symfony.com/doc/current/security/experimental_authenticators.html
    enable_authenticator_manager: true
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        # used to reload user from session & other features (e.g. switch_user)
        users:
            entity:
                class: App\Entity\Usuario
                property: username
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
#            anonymous: true
            lazy: true
            provider: users
            guard:
                authenticators:
                    - App\Security\LoginFormAuthenticator
            logout:
                path: app_logout
                # where to redirect after logout
            user_checker: App\Security\UserChecker
            switch_user: { role: ROLE_ADMIN, parameter: _want_to_be_this_user }

            # activate different ways to authenticate
            # https://symfony.com/doc/current/security.html#firewalls-authentication

            # https://symfony.com/doc/current/security/impersonating_user.html
            # switch_user: true

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/reset-password, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/jugador/precompetitivo, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/registro, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/confirmacion_precompetitivo/, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/ficha_precompetitiva/, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/ajax-public/, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/confirmacion-referee/, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/referee/inscripcion-ok/, role: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/admin/, role: ROLE_ADMIN }
        - { path: ^/admin/, role: ROLE_USER }
        - { path: ^/, role: IS_AUTHENTICATED_FULLY }
