twig:
    paths: ['%kernel.project_dir%/templates']
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
#    form_themes: ['bootstrap_4_layout.html.twig']
    form_themes:
            - 'bootstrap_3_layout.html.twig'
            - 'form/fields.html.twig'
            - 'TetranzSelect2EntityBundle:Form:fields.html.twig'
    globals:
        version: '%env(APP_VERSION)%'
        site_name: '%env(APP_SITE_NAME)%'
        union_name: '%env(APP_UNION_NAME)%'
        menu: '@App\Menu\Builder'
