<?php

namespace AppBundle\Repository;

/**
 * FichaMedicaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FichaMedicaRepository extends \Doctrine\ORM\EntityRepository
{
}
