<?php

namespace AppBundle\Repository;

/**
 * GrupoSanguineoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GrupoSanguineoRepository extends \Doctrine\ORM\EntityRepository
{
}
