<?php

namespace AppBundle\Repository;

/**
 * PagoJugadorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PagoJugadorRepository extends \Doctrine\ORM\EntityRepository {

	public function findQbByClub( $club ) {
		$qb = $this->createQueryBuilder( 'pj' );

		$qb->where( 'pj.club = :club' );

		$qb->setParameter( 'club', $club );

		return $qb;
	}
}
