<?php

namespace App\Repository;

/**
 * ClubRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClubRepository extends \Doctrine\ORM\EntityRepository {

	public function findQbAll() {
		return $this->createQueryBuilder( 'c' );
	}

	public function findQbBuscar( $data ) {
		$qb = $this->findQbAll();

		if ( $data ) {
			$nombre = $data['nombre'];
			$qb
				->where( "upper(c.nombre) like upper(:nombre)" );
			$qb->setParameter( 'nombre', '%' . $nombre . '%' );
		}

		return $qb;
	}
}
