<?php

namespace App\Repository;

/**
 * CondicionJugadorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CondicionJugadorRepository extends \Doctrine\ORM\EntityRepository
{
}
