<?php

namespace App\Repository;

/**
 * JugadorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JugadorRepository extends \Doctrine\ORM\EntityRepository {

	public function getQbAll() {
		$qb = $this->createQueryBuilder( 'j' );

		return $qb;
	}

	public function getJugadoresByClub( $club ) {
		$qb = $this->createQueryBuilder( 'j' );

		$qb->join( 'j.clubJugador', 'cj' )
		   ->join( 'cj.club', 'c' );

		$qb->where( 'c = :club' );
		$qb->andWhere( 'cj.confirmadoUnion = true' );

		$qb->setParameter( 'club', $club );


		return $qb;
	}

	public function getJugadores() {
		$qb = $this->createQueryBuilder( 'j' );

		$qb->join( 'j.clubJugador', 'cj' );

		$qb->andWhere( 'cj.confirmadoUnion = true' );

		return $qb;
	}

	public function getQbBuscarJugadores( $data ) {
		$qb = $this->createQueryBuilder( 'j' );

		$qb->join( 'j.clubJugador', 'cj' );

		$qb->andWhere( 'cj.confirmadoUnion = true' );
		$qb->andWhere( 'cj.confirmadoClub = true' );

		if ( isset( $data['numeroIdentificacion'] ) ) {
			$numeroIdentificacion = $data['numeroIdentificacion'];

			$qb->join( 'j.persona', 'persona' );

			$qb
				->where( "upper(persona.numeroIdentificacion) like upper(:numeroIdentificacion)" );
			$qb->setParameter( 'numeroIdentificacion', '%' . $numeroIdentificacion . '%' );
		}else{
			return [];
		}


		return $qb;
	}
}
