<?php

namespace App\Repository;

/**
 * PagoClubRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PagoClubRepository extends \Doctrine\ORM\EntityRepository {

	public function findQbAll() {
		return $this->createQueryBuilder( 'pc' );
	}
}
