<?php

namespace App\Repository;

/**
 * PosicionJugadorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PosicionJugadorRepository extends \Doctrine\ORM\EntityRepository
{
}
