<?php

namespace App\Repository;

/**
 * ResponsableJugadorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ResponsableJugadorRepository extends \Doctrine\ORM\EntityRepository
{
}
