<?php

namespace App\Repository;

/**
 * UnionsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UnionsRepository extends \Doctrine\ORM\EntityRepository
{
}
