jugador_index:
    path:     /
    defaults: { _controller: "AppBundle:Jugador:index" }
    methods:  GET

jugador_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Jugador:show" }
    methods:  GET

jugador_new:
    path:     /new
    defaults: { _controller: "AppBundle:Jugador:new" }
    methods:  [GET, POST]

jugador_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Jugador:edit" }
    methods:  [GET, POST]

jugador_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Jugador:delete" }
    methods:  DELETE

jugador_precompetitivo_presentacion:
    path:     /precompetitivo_presentacion
    defaults: { _controller: "AppBundle:Jugador:precompetitivoPresentacion" }
    methods:  [GET]

jugador_precompetitivo_categoria:
    path:     /precompetitivo_categoria
    defaults: { _controller: "AppBundle:Jugador:precompetitivoCategoria" }
    methods:  [GET]

jugador_precompetitivo_datos_personales:
    path:     /precompetitivo_datos_personales
    defaults: { _controller: "AppBundle:Jugador:precompetitivoDatosPersonales" }
    methods:  [GET, POST]

jugador_precompetitivo_datos_medicos_presentacion:
    path:     /precompetitivo_datos_medicos_presentacion
    defaults: { _controller: "AppBundle:Jugador:precompetitivoDatosMedicosPresentacion" }
    methods:  [GET]

jugador_precompetitivo_datos_medicos:
    path:     /precompetitivo_datos_medicos
    defaults: { _controller: "AppBundle:Jugador:precompetitivoDatosMedicos" }
    methods:  [GET]

jugador_precompetitivo_resumen:
    path:     /precompetitivo_resumen
    defaults: { _controller: "AppBundle:Jugador:precompetitivoResumen" }
    methods:  [GET]

jugador_precompetitivo_consentimiento:
    path:     /precompetitivo_consentimiento
    defaults: { _controller: "AppBundle:Jugador:precompetitivoConsentimiento" }
    methods:  [GET]

jugador_precompetitivo_ok:
    path:     /precompetitivo_ok/{id}
    defaults: { _controller: "AppBundle:Jugador:precompetitivoOk" }
    methods:  [GET]

jugador_precompetitivo:
    path:     /precompetitivo
    defaults: { _controller: "AppBundle:Jugador:precompetitivo" }
    methods:  [GET, POST]
