club_index:
    path:     /
    controller: App\Controller\ClubController::indexAction
#    methods:  GET

club_show:
    path:     /{id}/show
    controller: App\Controller\ClubController::showAction
#    methods:  GET

club_new:
    path:     /new
    controller: App\Controller\ClubController::newAction
#    methods:  [GET, POST]

club_edit:
    path:     /{id}/edit
    controller: App\Controller\ClubController::editAction
#    methods:  [GET, POST]

club_delete:
    path:     /{id}/delete
    controller: App\Controller\ClubController::deleteAction
#    methods:  DELETE
