clubjugador_index:
    path:     /
    controller: App\Controller\ClubJugadorController::indexAction
#    methods:  GET

clubjugador_show:
    path:     /{id}/show
    controller: App\Controller\ClubJugadorController::showAction
#    methods:  GET

clubjugador_confirmar:
    path:     /{id}/clubjugador_confirmar
    controller: App\Controller\ClubJugadorController::confirmarAction
#    methods:  [GET, POST]

clubjugador_rechazar:
    path:     /{id}/clubjugador_rechazar
    controller: App\Controller\ClubJugadorController::rechazarAction
#    methods:  [GET, POST]

clubjugador_reenviar_mail_confirmacion:
    path:     /{id}/clubjugador-reenviar-mail-confirmacion
    controller: App\Controller\ClubJugadorController::reenviarMailConfirmacion

clubjugador_confirmar_fichajes:
    path:     /confirmar-fichajes
    controller: App\Controller\ClubJugadorController::confirmarFichajes
    methods: POST
