#easy admin
easy_admin:
#    disabled_actions: ['delete']
#    site_name: "%site_name%"
    site_name: '%env(APP_SITE_NAME)%'
    show:
        max_results: 20
    list:
        actions:
            - { name: 'show', icon: 'eye', label: '' }
            - { name: 'edit', icon: 'pencil', label: '' }
            - { name: 'delete', icon: 'trash', label: '' }

    design:
        brand_color: '#3C8DBC'
#        form_theme: ['bootstrap_3_layout.html.twig']
        menu:
            - { label: 'Administración', route: 'app_homepage' }
            - { label: 'Configuración', entity: Configuracion , default: true}
            - { label: 'Condición Jugador', entity: CondicionJugador }
            - { label: 'Posición Jugador', entity: PosicionJugador }
            - { label: 'Categoría', entity: Categoria }
            - { label: 'División', entity: Division }
            - { label: 'Tipo Identificación', entity: TipoIdentificacion }
            - { label: 'Tipo Torneo', entity: TipoTorneo }
            - { label: 'Tipo Relación', entity: TipoRelacion }
            - { label: 'Sexo', entity: Sexo }
            - { label: 'Textos', entity: Texto }
            - { label: 'Personas', entity: Persona }
            - { label: 'Grupos Sanguineos', entity: GrupoSanguineo }
            - { label: 'País', entity: Pais }
            - { label: 'Usuarios', entity: Usuario }
        assets:
            favicon: 'bundles/app/img/logo.png'