easy_admin:
    entities:
        Pais:
            label: "País"
            class: App\Entity\Pais
            disabled_actions: ['delete']
            form:
                fields:
                - { property: 'nombre' }
                - { property: 'codigoPais' }
                - { property: 'codigoArea' }