easy_admin:
    entities:
        Sexo:
            label: "Sexo"
            class: App\Entity\Sexo
            disabled_actions: ['delete']
            form:
                fields:
                - { property: 'nombre' }