easy_admin:
    entities:
        Texto:
            label: "Textos"
            class: App\Entity\Texto
            disabled_actions: ['delete']
            form:
                fields:
                - { property: 'titulo' }
                - { property: 'descripcion' }
                - { property: 'cuerpo', type: 'ckeditor' }