easy_admin:
    entities:
        EstadoPartido:
            label: "Estado Partido"
            class: App\Entity\EstadoPartido
            disabled_actions: ['delete']
            form:
                fields:
                - { property: 'nombre' }