app_pagojugador:
    resource: "@AppBundle/Resources/config/routing/pagojugador.yml"
    prefix:   /pagojugador

app_pagoclub:
    resource: "@AppBundle/Resources/config/routing/pagoclub.yml"
    prefix:   /pagoclub

app_ajax:
    resource: "@AppBundle/Resources/config/routing/ajax.yml"
    prefix:   /ajax

app_ajax_public:
    resource: "@AppBundle/Resources/config/routing/ajax_public.yml"
    prefix:   /ajax-public

app_clubjugador:
    resource: "@AppBundle/Resources/config/routing/clubjugador.yml"
    prefix:   /clubjugador

app_persona:
    resource: "@AppBundle/Resources/config/routing/persona.yml"
    prefix:   /persona

app_jugador:
    resource: "@AppBundle/Resources/config/routing/jugador.yml"
    prefix:   /jugador

app_club:
    resource: "@AppBundle/Resources/config/routing/club.yml"
    prefix:   /club

app_homepage:
    path:     /
    defaults: { _controller: AppBundle:Default:index }
