app_pagojugador:
    resource: "routing/pagojugador.yaml"
    prefix:   /pagojugador

app_pagoclub:
    resource: "routing/pagoclub.yaml"
    prefix:   /pagoclub

app_ajax:
    resource: "routing/ajax.yaml"
    prefix:   /ajax

app_ajax_public:
    resource: "routing/ajax_public.yaml"
    prefix:   /ajax-public

app_clubjugador:
    resource: "routing/clubjugador.yaml"
    prefix:   /clubjugador

app_persona:
    resource: "routing/persona.yaml"
    prefix:   /persona

app_jugador:
    resource: "routing/jugador.yaml"
    prefix:   /jugador

app_club:
    resource: "routing/club.yaml"
    prefix:   /club

app_referee:
    resource: "routing/referee.yaml"
    prefix:   /referee

app_pase:
    resource: "routing/pase.yaml"
    prefix:   /pase

app_homepage:
    path:     /
    controller: App\Controller\DefaultController::indexAction

confirmacion_precompetitivo:
    path:     /confirmacion_precompetitivo/{token}
    controller: App\Controller\JugadorController::precompetitivoConfirmacionAction
#    methods:  GET

jugador_ficha_precompetitiva:
    path:     /ficha_precompetitiva/{clubJugadorId}
    controller: App\Controller\JugadorController::fichaPrecompetitivaAction
#    methods:  [GET]

jugador_registro:
    path:     /registro
    controller: App\Controller\JugadorController::precompetitivoAction
#    methods:  [GET, POST]

#referee
confirmacion_referee:
    path:     /confirmacion-referee/{token}
    controller: App\Controller\RefereeController::confirmacionInscripcion