#easy admin
easy_admin:
#    disabled_actions: ['delete']
    site_name: "%site_name%"
    show:
        max_results: 20
    list:
        actions:
            - { name: 'show', icon: 'eye', label: '' }
            - { name: 'edit', icon: 'pencil', label: '' }
            - { name: 'delete', icon: 'trash', label: '' }

    design:
        brand_color: '#3C8DBC'
        form_theme: ['AppBundle:Form:bootstrap_3_layout.html.twig']
        menu:
            - { label: 'Condición Jugador', entity: CondicionJugador , default: true}
            - { label: 'Posición Jugador', entity: PosicionJugador }
            - { label: 'Categoría', entity: Categoria }
            - { label: 'Tipo Identificación', entity: TipoIdentificacion }
            - { label: 'Sexo', entity: Sexo }
            - { label: 'País', entity: Pais }
            - { label: 'Usuarios', entity: Usuario }
        assets:
            favicon: 'bundles/app/img/logo.png'
#
#    assets:
#        css:
#            - 'bundles/app/plugins/datepicker/datepicker3.css'
#            - 'bundles/app/plugins/daterangepicker/daterangepicker.css'
#            - 'bundles/app/plugins/timepicker/bootstrap-timepicker.min.css'
#            - 'bundles/app/plugins/fontawesome-iconpicker/css/fontawesome-iconpicker.min.css'
#            - 'bundles/app/css/admin.css'
#        js:
#            - "https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.11.2/moment.min.js"
#            - 'bundles/app/plugins/daterangepicker/daterangepicker.js'
#            - 'bundles/app/plugins/datepicker/bootstrap-datepicker.js'
#            - 'bundles/app/plugins/datepicker/locales/bootstrap-datepicker.es.js'
#            - 'bundles/app/plugins/fontawesome-iconpicker/js/fontawesome-iconpicker.min.js'
#            - 'bundles/app/js/admin.js'