easy_admin:
    entities:
        GrupoSanguineo:
            label: "Grupo Sanguineos"
            class: AppBundle\Entity\GrupoSanguineo
            disabled_actions: ['delete']
            form:
                fields:
                - { property: 'nombre' }
                - { property: 'descripcion' }