easy_admin:
    entities:
        PosicionJugador:
            label: "Posición Jugador"
            class: AppBundle\Entity\PosicionJugador
            disabled_actions: ['delete']
            form:
                fields:
                - { property: 'numero' }
                - { property: 'nombre' }